import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from "next/router";

import styles from '../../styles/HorseClubs.module.css';

export default function HorseClubs() {
    const router = useRouter();
    const id = router.query.id;

    return (
        <div className={styles.container}>
            <Head>
                <title>Horse Clubs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href='/'>Back to home</Link>
                Horse Clubs {id}
            </main>

        </div>
    )
}
