import Head from 'next/head';
import Image from 'next/image';

import Banner from '../components/Banner';
import ClubCard from '../components/ClubCard/ClubCard';
import Layout from '../components/Layout/Layout';


import { fetchHorseClubs } from '../lib/horse-clubs';

import styles from '../styles/Home.module.css';


export default function Home(props) {

  const btnClickHandler = () => { };

  return (
    <div>
      <Head>
        <title>Equestrian portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner clickHandler={btnClickHandler} btnText="Horse Clubs nearby" />
        <div className={styles.heroImage}>
          <Image src="/static/hero-horse-home.png" width={400} height={463} />
        </div>

        {props.horseClubs.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Horse Clubs near me</h2>
            <div className={styles.cardLayout}>
              {props.horseClubs.map((club) => <ClubCard
                key={club.id}
                name={club.name}
                imgUrl={club.imgUrl}
                href={`/horse-clubs/${club.id}`} />)}
            </div>
          </div>
        )}
      </Layout>

    </div>
  )
}

export async function getStaticProps(context) {
  const horseClubs = await fetchHorseClubs();

  return {
    props: {
      horseClubs,
    },
  };
}
