import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import styles from '../styles/Home.module.css';

export default function Home() {

  const btnClickHandler = () => { };

  return (
    <div className={styles.container}>
      <Head>
        <title>Equestrian portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner clickHandler={btnClickHandler} btnText="Horse Clubs nearby" />
        <div className={styles.heroImage}>
          <Image src="/static/hero-horse-home.png" width={400} height={463} />
        </div>
      </main>

    </div>
  )
}
